Capstone project
MPDADDY/capstone_project pull request #1
Opened 2023-05-31 19:08 UTC by MPDADDY

- [ ] Project has a mobile version with a hamburger menu 
- [ ] A desktop version with other menus that don't display by default on the mobile version
- [ ] A section of featured speakers that are displayed dynamically using javascript.

2023-05-31 20:58 UTC, zieeco requested changes
Hi @MPDADDY,


<img height="220" src="https://media4.giphy.com/media/Cm9wKmKMUlRPvdoHgU/giphy-downsized-medium.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice code organization.✔️
- Nice design. ✔️
- Descriptive PR. ✔️
- Nice implementation :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 20:58 UTC, zieeco commented on index.html
> +      </div>
## HOME AND ABOUT PAGE NAV

- Hey, while you've added only on nav, the homepage and about pages have two nav, which are the top and bottom navbars. please, kindly check the design to implement the missing top nav. see the images below:


*main design*
![image](https://github.com/MPDADDY/capstone_project/assets/59397159/c891ddb5-0ea3-4973-be80-ee2d86880eec)

*your design*
![image](https://github.com/MPDADDY/capstone_project/assets/59397159/ab7e8078-a3cd-444d-af0d-54ca146f042b)

2023-05-31 20:58 UTC, zieeco commented on index.html
> +        </div>
- Hey, your logo in the design is different from the one in the footer, as this is not an ideal design pattern in a webpage, please, consider having the same logo across all pages in your design, ie, homepage, about page, and footer.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +    </footer>
- Hey, your logo here in the footer is different from that in the header, as this is not an ideal design pattern in a webpage, please, consider having the same logo across all pages in your design, ie, homepage, about page, footer.
- Also, it is not semantically correct to have your footer nested in your `main`. The footer is a standalone part of a webpage always found at the bottom end of the webpage and as such, doesn't need to be nested in the `main` tag of your webpage. Please, kindly remove the footer from the main.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +    </nav>
- Hey, you seem to have a closing nav tag without the opening nav here, kindly double-check it to fix this issue.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +          <img src="images/naver 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +        <img src="images/cck-logo1 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +          <img src="images/program_icon_03 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +          <img src="images/program_icon_04 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +          <img src="images/program_icon_05 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +          <img src="images/program_icon_02 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: '<img src="images/speaker_01 1 (5).png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: '<img src="images/speaker_01 1.png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: '<img src="images/speaker_01 1 (3).png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: ' <img src="images/speaker_01 1 (1).png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: '<img src="images/speaker_01 1 (4).png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +    image: '<img src="images/speaker_01 1 (2).png" alt="">',
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on script.js
> +morebtn.addEventListener('click', displayList); */
- Hey, let's kindly remove all these commented codes from the codebase to make it clean, maintainable, and readable.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +      </div>
## HOME AND ABOUT PAGE NAV

- Hey, while you've added only on nav, the homepage and about pages have two nav, which are the top and bottom navbars. please, kindly check the design to implement the missing top nav. see the images below:


*main design*
![image](https://github.com/MPDADDY/capstone_project/assets/59397159/c891ddb5-0ea3-4973-be80-ee2d86880eec)

*your design*
![image](https://github.com/MPDADDY/capstone_project/assets/59397159/ab7e8078-a3cd-444d-af0d-54ca146f042b)

2023-05-31 20:58 UTC, zieeco commented on about.html
> +  </footer>
- Hey, your logo here in the footer is different from that in the header, as this is not an ideal design pattern in a webpage, please, consider having the same logo across all pages in your design, ie, homepage, about page, footer.
- Also, it is not semantically correct to have your footer nested in your `main`. The footer is a standalone part of a webpage always found at the bottom end of the webpage and as such, doesn't need to be nested in the `main` tag of your webpage. Please, kindly remove the footer from the main.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +    </article>
- Hey, according to the main design on the desktop version of the About page, the partner section is hidden but only visible on the mobile version of the About page. let's improve on this.
- Also, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +      <img src="images/cck-logo1 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +        <img src="images/about_2013 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +         <img src="images/about_logo 1.png" alt="">
- Hey, to improve the web accessibility of your page, let's add the alternative missing text to our image in case they fail to load to aid the visually impaired users.

2023-05-31 20:58 UTC, zieeco commented on about.html
> +        </div>
- Hey, your logo in the design is different from the one in the footer, as this is not an ideal design pattern in a webpage, please, consider having the same logo across all pages in your design, ie, homepage, about page, footer.

2023-05-31 20:58 UTC, zieeco commented on index.html
> +      </div>
- Hey, Please, let's try to adhere to the project requirement as much as we can as seen below, and try to make the necessary updates:

![image](https://github.com/MPDADDY/capstone_project/assets/59397159/016e4978-c3cc-4c0c-acaa-3fdf51990c69)

2023-05-31 20:58 UTC, zieeco commented on about.html
> +      <div class="summit_logo">
- Hey, Please, let's try to adhere to the project requirement as much as we can as seen below, and try to make the necessary updates:

![image](https://github.com/MPDADDY/capstone_project/assets/59397159/016e4978-c3cc-4c0c-acaa-3fdf51990c69)

2023-05-31 20:58 UTC, zieeco commented on styles.css
> +  }
- Hey, please, let's kindly add the missing white border when each card are being hovered to improve the user experience of your website as seen in the image below:


![image](https://github.com/MPDADDY/capstone_project/assets/59397159/d40c37d3-8e33-4a2f-afdf-f3b3d07bf666)

2023-05-31 20:58 UTC, zieeco commented on README.md
> +-->
- Hey, let's remove these commented pieces of code to make the codebase clean and maintainable.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +
- Hey, let's remove these commented pieces of code to make the codebase clean and maintainable.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- Hey, as this is a main requirement for this project, kindly add a live demo link by making use of GitHub Pages to deploy the web.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +  git clone git@github.com:MPDADDY/portfolio.git
- Hey, let's ensure you've added the correct link to this current project to improve your readme.

2023-05-31 20:58 UTC, zieeco commented on README.md
> + -->
- Hey, let's remove these commented pieces of code to make the codebase clean and maintainable.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +
- Hey, in this section, you're meant to tell users what platform the website could be deployed on, in your case, it is Github Pages. please, update it as the link you've added should only be added in the live demo link.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +
- Hey, since you won't add any test in this project, kindly remove this section to make your readme only have the content relevant to your project making it more professional.

2023-05-31 20:58 UTC, zieeco commented on README.md
> +  gem install
- Hey, this should be `npm install` and not gem install as this is a html-css-javascript project and not a ruby project. let's kindly update this.

2023-06-01 09:57 UTC, Ismailco requested changes
#### Hi @MPDADDY, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-01 09:57 UTC, Ismailco commented on index.html
> +          </li>
- [ ] [OPTIONAL] Great job creating the navbar however kindly consider adding some more height to the top bar and make sure the bottom bar has the correct color for the nav links, also the logo and the links should be aligned in the center of the nav bar. kindly make sure to fix this issues so your website looks more semantic

2023-06-01 09:57 UTC, Ismailco commented on index.html
> +      <button id="readmore" class="speakerbtn" type="submit">MORE <img class="arrowdown" src="images/arrow_down 1.png" alt="">
- [ ] [OPTIONAL] Kindly make sure all the `img` tags in your code have an `alt` attribute with the proper text

2023-06-01 09:57 UTC, Ismailco commented on index.html
> +          <img src="images/naver 1.png" alt="">
- [ ] Kindly make sure to add a text for the `img` `alt` attribute as the previous reviewer suggested

2023-06-01 09:57 UTC, Ismailco commented on about.html
> +  <title>Document</title>
- [ ] [OPTIONAL] Kindly make sure the HTML title is descriptive and reflects the project name

2023-06-01 09:57 UTC, Ismailco commented on about.html
> +    </nav>
- [ ] [OPTIONAL] Same for the about page navbar kindly consider adding some more height to the top bar and make sure the bottom bar has the correct color for the nav links, also the logo and the links should be aligned in the center of the nav bar. kindly make sure to fix this issues so your website looks more semantic

2023-06-01 09:57 UTC, Ismailco commented on about.html
> +  </footer>
- [ ] As the previous reviewer suggested kindly make sure to move the `footer` section outside of the `main` section

2023-06-01 09:57 UTC, Ismailco commented on index.html
> +        <h1>CREATIVE COMMONS <br> GLOBAL CONCERT <br> 2023</h1>
- [ ] As the previous reviewer mentioned kindly make sure to personalize your project to your need, make sure to change the event name and you can use different images and logos

2023-06-01 09:57 UTC, Ismailco commented on styles.css
> +  }
- [ ] As the previous reviewer mentioned kindly add the missing white border when each card is being hovered to improve the user experience of your website as seen in the image below:
![](https://user-images.githubusercontent.com/59397159/242404522-d40c37d3-8e33-4a2f-afdf-f3b3d07bf666.png)

2023-06-01 09:57 UTC, Ismailco commented on README.md
> +-->
- [ ] Kindly make sure to remove the comments in your README file so it looks clean and easy to navigate when accessing it from a test editor

2023-06-01 09:57 UTC, Ismailco commented on README.md
> +
- [ ] Kindly make sure to add a deployed version of your website to the `Live demo` section in your README so users can access the website

2023-06-01 09:57 UTC, Ismailco commented on README.md
> +  git clone git@github.com:MPDADDY/portfolio.git
- [ ] Kindly make sure to use the correct repo link after ` git clone....`

2023-06-01 09:57 UTC, Ismailco commented on README.md
> +- click [capstone_project](https://mpdaddy.github.io/capstone_project/) for the deployed site.
- [ ] This section should include instructions on how to deploy the project if the user decided to do this on their own, the deployed website link should be in the `Live demo` section not here

2023-06-01 09:57 UTC, Ismailco commented on README.md
> +  npm install
- [ ] [OPTIONAL] Are you using npm for this project? if not this is irrelevant and you should remove it, kindly make sure to customize your documentations for this project

2023-06-01 11:45 UTC, binhussen approved these changes
Hi @MPDADDY , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Fixed Request Changes ✔️
- Well-structured Code✔️
- Sticked given Design ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 12:07 UTC, merged